version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx_admin_template.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: bitnami/php-fpm:7.3-prod
    volumes:
      - ./:/code
    networks:
      - code-network
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /home/kk/git/php/test/db:/var/lib/mysql
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
